
package com.nisira.clientservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SignServiceException", targetNamespace = "http://core.sign.nisira.com")
public class SignServiceException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SignServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SignServiceException_Exception(String message, SignServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SignServiceException_Exception(String message, SignServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.nisira.clientservice.SignServiceException
     */
    public SignServiceException getFaultInfo() {
        return faultInfo;
    }

}
