
package com.nisira.clientservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SignServicePortType", targetNamespace = "http://core.sign.nisira.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SignServicePortType {


    /**
     * 
     * @param idempresa
     * @param var3
     * @param claveempresa
     * @param var2
     * @param var0
     * @param claveusuario
     * @param idusuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:consulta001")
    @WebResult(targetNamespace = "http://core.sign.nisira.com")
    @RequestWrapper(localName = "consulta001", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.Consulta001")
    @ResponseWrapper(localName = "consulta001Response", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.Consulta001Response")
    public String consulta001(
        @WebParam(name = "var0", targetNamespace = "http://core.sign.nisira.com")
        String var0,
        @WebParam(name = "var2", targetNamespace = "http://core.sign.nisira.com")
        String var2,
        @WebParam(name = "var3", targetNamespace = "http://core.sign.nisira.com")
        String var3,
        @WebParam(name = "idempresa", targetNamespace = "http://core.sign.nisira.com")
        int idempresa,
        @WebParam(name = "claveempresa", targetNamespace = "http://core.sign.nisira.com")
        String claveempresa,
        @WebParam(name = "idusuario", targetNamespace = "http://core.sign.nisira.com")
        String idusuario,
        @WebParam(name = "claveusuario", targetNamespace = "http://core.sign.nisira.com")
        String claveusuario);

    /**
     * 
     * @param idempresa
     * @param var6
     * @param var5
     * @param var4
     * @param var3
     * @param claveempresa
     * @param var2
     * @param var0
     * @param claveusuario
     * @param idusuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:consultaIndividual")
    @WebResult(targetNamespace = "http://core.sign.nisira.com")
    @RequestWrapper(localName = "consultaIndividual", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.ConsultaIndividual")
    @ResponseWrapper(localName = "consultaIndividualResponse", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.ConsultaIndividualResponse")
    public String consultaIndividual(
        @WebParam(name = "var0", targetNamespace = "http://core.sign.nisira.com")
        String var0,
        @WebParam(name = "var2", targetNamespace = "http://core.sign.nisira.com")
        String var2,
        @WebParam(name = "var3", targetNamespace = "http://core.sign.nisira.com")
        String var3,
        @WebParam(name = "var4", targetNamespace = "http://core.sign.nisira.com")
        String var4,
        @WebParam(name = "var5", targetNamespace = "http://core.sign.nisira.com")
        String var5,
        @WebParam(name = "var6", targetNamespace = "http://core.sign.nisira.com")
        String var6,
        @WebParam(name = "idempresa", targetNamespace = "http://core.sign.nisira.com")
        int idempresa,
        @WebParam(name = "claveempresa", targetNamespace = "http://core.sign.nisira.com")
        String claveempresa,
        @WebParam(name = "idusuario", targetNamespace = "http://core.sign.nisira.com")
        String idusuario,
        @WebParam(name = "claveusuario", targetNamespace = "http://core.sign.nisira.com")
        String claveusuario);

    /**
     * 
     * @param idempresa
     * @param xml
     * @param documento
     * @param claveempresa
     * @param adicional
     * @param claveusuario
     * @param idusuario
     * @return
     *     returns java.lang.String
     * @throws SignServiceException_Exception
     */
    @WebMethod(action = "urn:sign")
    @WebResult(targetNamespace = "http://core.sign.nisira.com")
    @RequestWrapper(localName = "sign", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.Sign")
    @ResponseWrapper(localName = "signResponse", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.SignResponse")
    public String sign(
        @WebParam(name = "documento", targetNamespace = "http://core.sign.nisira.com")
        String documento,
        @WebParam(name = "xml", targetNamespace = "http://core.sign.nisira.com")
        String xml,
        @WebParam(name = "idempresa", targetNamespace = "http://core.sign.nisira.com")
        int idempresa,
        @WebParam(name = "claveempresa", targetNamespace = "http://core.sign.nisira.com")
        String claveempresa,
        @WebParam(name = "idusuario", targetNamespace = "http://core.sign.nisira.com")
        String idusuario,
        @WebParam(name = "claveusuario", targetNamespace = "http://core.sign.nisira.com")
        String claveusuario,
        @WebParam(name = "adicional", targetNamespace = "http://core.sign.nisira.com")
        String adicional)
        throws SignServiceException_Exception
    ;

    /**
     * 
     * @param idempresa
     * @param claveempresa
     * @param claveusuario
     * @param idusuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:consultaEstadoCertificado")
    @WebResult(targetNamespace = "http://core.sign.nisira.com")
    @RequestWrapper(localName = "consultaEstadoCertificado", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.ConsultaEstadoCertificado")
    @ResponseWrapper(localName = "consultaEstadoCertificadoResponse", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.ConsultaEstadoCertificadoResponse")
    public String consultaEstadoCertificado(
        @WebParam(name = "idempresa", targetNamespace = "http://core.sign.nisira.com")
        int idempresa,
        @WebParam(name = "claveempresa", targetNamespace = "http://core.sign.nisira.com")
        String claveempresa,
        @WebParam(name = "idusuario", targetNamespace = "http://core.sign.nisira.com")
        String idusuario,
        @WebParam(name = "claveusuario", targetNamespace = "http://core.sign.nisira.com")
        String claveusuario);

    /**
     * 
     * @param idempresa
     * @param ticket
     * @param documento
     * @param claveempresa
     * @param claveusuario
     * @param idusuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:consulta")
    @WebResult(targetNamespace = "http://core.sign.nisira.com")
    @RequestWrapper(localName = "consulta", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.Consulta")
    @ResponseWrapper(localName = "consultaResponse", targetNamespace = "http://core.sign.nisira.com", className = "com.nisira.clientservice.ConsultaResponse")
    public String consulta(
        @WebParam(name = "documento", targetNamespace = "http://core.sign.nisira.com")
        String documento,
        @WebParam(name = "ticket", targetNamespace = "http://core.sign.nisira.com")
        String ticket,
        @WebParam(name = "idempresa", targetNamespace = "http://core.sign.nisira.com")
        int idempresa,
        @WebParam(name = "claveempresa", targetNamespace = "http://core.sign.nisira.com")
        String claveempresa,
        @WebParam(name = "idusuario", targetNamespace = "http://core.sign.nisira.com")
        String idusuario,
        @WebParam(name = "claveusuario", targetNamespace = "http://core.sign.nisira.com")
        String claveusuario);

}
